import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import { AuthProvider } from "./Providers";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`p-5 [background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#63e_100%)]`}>
        <Header />
        <div className="pb-56">
          <AuthProvider>{children}</AuthProvider>
        </div>
        <Footer />
      </body>
    </html>
  );
}