import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`p-5 [background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#63e_100%)]`}>
      <div className="text-white mt-[-10px] flex justify-between">
            <Image src="/logo.png" width={150} height={150} alt="logo"/>
            <div className="mt-5">
                <a href="/" className="rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white" aria-current="page">Эхлэл</a>
                <a href="/comingsoon" className="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Тун удахгүй</a>
                <a href="/hutulbur" className="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Цагийн хуваарь</a>
                <a href="#" className="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Үйлчилгээ</a>
                <a href="#" className="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Бонус карт</a>
            </div>
            <div className="mt-5">
                <a type="button" href="/login" className="text-white bg-gradient-to-r from-gray-500 via-gray-600 to-gray-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-gray-300 dark:focus:ring-gray-800 shadow-lg shadow-gray-500/50 dark:shadow-lg dark:shadow-gray-800/80 font-bold rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2">Нэвтрэх</a>
            </div>
        </div>
        {children}
        <div className="m-auto w-[1000px] h-full flex justify-between pt-10 pb-10">
            <div className="pl-10">
                <h1 className="text-white font-bold text-2xl pb-5">ҮНДСЭН</h1>
                <h1 className="text-white">Эхлэл</h1>
                <h1 className="text-white">Тун удахгүй</h1>
                <h1 className="text-white">Хөтөлбөр</h1>
                <h1 className="text-white">Үйлчилгээ</h1>
                <h1 className="text-white">Бонус карт</h1>
            </div>
            <div>
                <h1 className="text-white font-bold text-2xl pb-5">ХОЛБООС</h1>
                <h1 className="text-white">Facenook</h1>
                <h1 className="text-white">Instagram</h1>
                <h1 className="text-white">Youtube</h1>
            </div>
            <div className="pr-10">
                <h1 className="text-white font-bold text-2xl pb-5">ТУСЛАХ ЦЭС</h1>
                <h1 className="text-white">Салбар</h1>
                <h1 className="text-white">Бонус карт</h1>
                <h1 className="text-white">Нэвтрэх</h1>
                <h1 className="text-white">Урамшуулал</h1>
                <h1 className="text-white">Үйлчилгээний нөхцөл</h1>
            </div>
        </div>
      </body>
    </html>
  );
}